### ISSUE TITLE
where is v9.7.0-33-g538a5023af

### ISSUE THREAD

**Issue by epicylq** [electron/node#99]
electron 3.1.7  dep node version is  v9.7.0-33-g538a5023af, but i can't find it, any one know where is it ?

**Comment by willjoha** [comment]
I was also looking for the same commit while I tried to build the electron version (v3.1.8) used in VSCode myself.

The commit is not available anymore in this repository because someone deleted the branch electron-node-v9.7.0 which received the pull request electron#35

The fork https://github.com/ganlingchang/node still contains the required branch.
In addition I just created a fork of the ganlingchang/node repository in case it will be deleted in the meantime.

From my point of view the electron-node-v9.7.0 branch should be pushed again into this repository since the commit is referenced in released electron versions.

**Comment by zcbenz** [comment]
Thanks for finding out the fork with the branch, I have pushed it to the repo.
